### ISSUE TITLE
Integration with nvim-lsp

### ISSUE THREAD

**Issue by famiu** [hardcoreplayers/spaceline.vim#26]
Hey, so I checked this out and really liked it, but the only problem is that it has a dependency on coc.nvim, I personally don't use it, rather I use Neovim's new built-in LSP client (which I find to be much better). Would it be possible to integrate it with Neovim's native LSP client and not use coc.nvim?

**Comment by glepnir** [comment]
Glad to hear this, I will check nvim-lsp, but what is the difference between nvim-lsp and coc? nvim-lsp uses some unmaintained servers...If I have time I will try to add support for nvim-lsp.

**Comment by famiu** [comment]
nvim-lsp is much faster and better integrated, for me at least, it's a much better choice than coc.

**Comment by glepnir** [comment]
Aha , i will check it later.

**Comment by glepnir** [comment]
I had refactor spaceline. now it's easy to do that ,Only need to perfect these two functions. Since I have no time to check nvim-lsp recently. PR welcome.
https://github.com/hardcoreplayers/spaceline.vim/blob/cf96e952ba03e7105a035a287bf30ba0d21dfe17/autoload/spaceline/diagnostic.vim#L58

https://github.com/hardcoreplayers/spaceline.vim/blob/cf96e952ba03e7105a035a287bf30ba0d21dfe17/autoload/spaceline/diagnostic.vim#L63

**Comment by glepnir** [comment]
I had add nvim-lsp support.please test.

**Comment by famiu** [comment]
@glepnir Initially it didn't work, but after changing the function names s:nvim_lsp_error() to s:diagnostic_nvim_lsp_error() and s:nvim_lsp_warn() to s:diagnostic_nvim_lsp_warn, it worked. Thanks a lot

**Comment by glepnir** [comment]
@Famiu  Aha. my mistake. fixed.

**Comment by glepnir** [comment]
Added two options to change the sign.
```viml
g:spaceline_nvim_lsp_errorsign
g:spaceline_nvim_lsp_warnsign
```

**Comment by glepnir** [comment]
another question is  if don't install coc the git diff should be not depend on coc-git. so we need find a new way to support git diff.

**Comment by glepnir** [comment]
now spaceline can show the git branch info without `coc-git`
