### ISSUE TITLE
looks weird when just input `nvim` and enter on shell

### ISSUE THREAD

**Issue by mxarcher** [hardcoreplayers/spaceline.vim#63]
**arrow-fade**
![1](https://user-images.githubusercontent.com/44336929/105629324-567eb700-5e7d-11eb-97e9-79184be7cf1e.png)
**arrow**
![2](https://user-images.githubusercontent.com/44336929/105629650-436ce680-5e7f-11eb-9aac-8ed17f25ed3e.png)
**curve**
![image](https://user-images.githubusercontent.com/44336929/105629692-8464fb00-5e7f-11eb-82dc-5998df312df1.png)
**slant**
![image](https://user-images.githubusercontent.com/44336929/105629727-b4ac9980-5e7f-11eb-9f82-85185fd36a52.png)
**slant-fade**
![image](https://user-images.githubusercontent.com/44336929/105629764-e58cce80-5e7f-11eb-9894-8d82da3fd946.png)
**slant-cons**
![image](https://user-images.githubusercontent.com/44336929/105629808-297fd380-5e80-11eb-8d44-edffdc6aff3c.png)

Is the display result correct?

terminal emulator: xfce4-terminal
neovim version: v0.5.0-dev

min vimrc:
```sh
 set termguicolors
 set runtimepath+=~/.cache/nvim/dein/repos/github.com/arcticicestudio/nord-vim
 set runtimepath+=~/.cache/nvim/dein/repos/github.com/kyazdani42/nvim-web-devicons
 set runtimepath+=~/.cache/nvim/dein/repos/github.com/glepnir/spaceline.vim
 colorscheme nord
 let g:spaceline_seperate_style = "arrow-fade"
 let g:spaceline_colorscheme = "nord"
```

**Comment by mxarcher** [comment]
@glepnir 
thx for the very quickly fix
but does spaceline support nord colorscheme?

it work well on 'one'
![image](https://user-images.githubusercontent.com/44336929/105630955-ce051400-5e86-11eb-8e5d-9ea6ae0dd9a4.png)
however
![image](https://user-images.githubusercontent.com/44336929/105630993-0147a300-5e87-11eb-80dc-73043b80f7e3.png)

**Comment by glepnir** [comment]
hmm I am not spaceline nord colorscheme author and I most suggest that used [galaxyline](https://github.com/glepnir/galaxyline.nvim). 

you can use `set statusline?` to check which separetor group color is wrong and fixed it in spaceline/nord.vim .then send PR

**Comment by folliehiyuki** [comment]
Hi I was the one making the Nord theme for spaceline.
That last character is `emptySeperate1`, so revert the fix above will make it look normal when you are opening a file.
Other themes have the 1st problem too, so I suggest we just revert the fix (no one probably sees a blank nvim most of the time anyway).
The better way might be setting that character to a color depending on the block on its left, but that seems complicating for what it's worth. It's up to @glepnir to decide.
Though, seeing that you are using neovim 0.5-dev, I agree that galaxyline might suite you better if this problem is troublesome to you.
